title: Requesting test funds
body:
  - type: markdown
    attributes:
      value: |
        Here you may request funds from Entropy for use with the Entropy test network (testnet). You must have an entropy account to make this request. Accounts can be created using the Entropy CLI. [Follow the quickstart guide for more information](https://docs.entropy.xyz/).
  - type: input
    id: contact
    attributes:
      label: Address
      description: Your entropy address
      placeholder: 5E6iCTbq...
    validations:
      required: true
