title: "Fund Request"
body:
  - type: markdown
    attributes:
      value: |
        ## Test Fund Request
        ##
        Here you may request funds from Entropy for use with the
        Entropy TestNet. You will need an entropy account and the account's address to
        make this request. Accounts can be created using our cli. Follow our
        [Quicktart Guide](https://docs.entropy.xyz/) to get started.

        By default, you will be funded 10,000 test funds. If you need more,
        please specify why in the request.

  - type: input
    id: address
    attributes:
      label: Entropy address
      description: What is your entropy address?  This can be found with the cli and going to Manage Accounts > List Accounts and finding the "address" value in your chosen account.
      validations:
        required: true

  - input: dropdown
    id: require-more-funds
    attributes:
      label: Do you require more than 10,000 test funds?
      options:
        - Yes
        - No
      default: 1

  - input: textarea
    id: fund-request-reason
    attributes:
      label: If you selected yes above, please tell us why
      description: Please provide the context and reason for any fund request above the standard 10,000.

  - type: markdown
    attributes:
      value: |
        ## Thanks

        Upon submission, someone from Entropy will send the funds to your
        address. This usually takes a couple of hours, but may take more.

        Thanks!
